[package]
name = "table-format"
version = "0.0.1"
authors = ["Stuart Thompson <stuart@stuartthompson.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"